### ISSUE TITLE
Account Registration

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/Taste-Buds-Restaurant-App#1]
As a **site user** I can **register an account**  so that  **I can manage my booking**

## Acceptance Criteria

* Register Account requires name, email and password
* After Register, redirect to Homepage with SignOut option in navigation bar 

## Task
- [x] Create Register option in navigation bar and link to register form
- [x] Create base page, Home page 
- [x] Setup account registration using Django's allauth library
- [x] Create custom form in order to register with name, email, password
- [x] setup navbar to highlight SignOut in status

**Comment by bijokmathew** [comment]
Done all the listed task and verified
