### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/Taste-Buds-Restaurant-App#10]
As a **authorized site user ** I can  **reset my password** so that **I can reset my password and login to home page **

## Acceptance Criteria

* Authorized site user is able to receive a password reset email, which allows them to follow a link and reset their password.
* It should only be possible to send password reset links to email addresses stored in the User Model.
*
## Task
- [ ] create email backend on django with gmail
- [ ] register the company's email in settings for the backend.
- [ ] update config vars on heroku with email details.
- [ ] add the required html templates from the allauth package to handle functionality.
- [ ] create the custom email template.
