### ISSUE TITLE
Booking Table

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/Taste-Buds-Restaurant-App#2]
As a **customer** I can ** book a table** so that **I can make my reservation at the restaurant**

## Acceptance Criteria

*  Customer can view 'booking table' option on hero section in the home page and navigation bar 
*  Customer can view booking table form with name, number of guest, phone, email, date and time 
*  If customer is not sign In  then show the message to the user for  SignIn /SignUp
*  After booking redirect to my booking page which should list all the bookings related to the particular user

## Task
- [x] Create database schema and model for booking table
- [x] Migrate the model to the database
- [x] Register the model in admin.py
- [x] Create a booking form with name, email, phone number, number of guest, date and time
- [x] Handle the POST requests in the views.py for booking the table.
- [x] Create my booking page   
- [x]  After booking table, redirect to my booking page

**Comment by bijokmathew** [comment]
Done all the listed task and verified
