### ISSUE TITLE
View all table Bookings

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/Taste-Buds-Restaurant-App#3]
As a **site admin** I can **view all table booking** so that **I can modify/delete booking based on the request**

## Acceptance Criteria

*  Admin can view  all customer bookings
*  Admin can modify and cancel booking based on the user request 
*  Admin can filter the booking list based on the date of booking
*  Admin can view the name, number of guest, date and time of booking on the admin panel
*  Admin can search booking details based on name or date

## Task
- [x]  Create admin panel using Django built in admin panel 
- [x]  Create filter based on the booking date 
- [x]  Create a search field to search on name ,booking time and number of guest
- [x]  Create a list of filed like name, number of guest, date , time and booking status to display on the booking list

**Comment by bijokmathew** [comment]
All the listed job done and tested
