### ISSUE TITLE
Manage My Booking

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/Taste-Buds-Restaurant-App#4]
As a **a customer** I can ** view all my bookings** so that **I can modify or cancel the booking if required**

## Acceptance Criteria

*  Customer can view all his booking details after selecting the “My booking”
*  Customer can Edit/Cancel his booking 
*  Customer can view confirmation alert after selecting delete option on booking details

## Task
- [x] Create a class using generic in views for rendering booking details on booking_details.html template.
- [x] Search all booking and Filter by current user booking from the booking table.
- [x] Iterate over the users booking within the template and display within a card.
- [x] Test the display of the booking details as per the requirements.
- [x] Create edit form for updating the specific existing booking detail
- [x] Create delete functionality for deleting the specific booking

**Comment by bijokmathew** [comment]
All the listed tasks done and tested
