### ISSUE TITLE
Double Bookings

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/Taste-Buds-Restaurant-App#7]
As a **admin** I can ** avoid double booking of a customer ** so that **I can manage booking without any confusion**

## Acceptance Criteria

*  Registered customers are prevented from making a booking table again on that time stamp which already booked by the same user 

*  Customer can  view alert like 'A double booking request being made'.

## Task
- [x] Add unique constraint to Booking table model for user, date and time field.
- [x] Add try/except to amend and booking view to test constraint met.
- [x] Create alert to display the message to the customer if not met

**Comment by bijokmathew** [comment]
Finished all the listed task and tested
