### ISSUE TITLE
View the Restaurant Menu

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/Taste-Buds-Restaurant-App#8]
As a **customer** I can **view the restaurant menu list** so that **I can decide what to order**

## Acceptance Criteria

*  Customer can view the 'Menu' on the landing page.
*  Customer can view the menu and read it's content.
*  Customer can go to menu items from the navigation bar.

## Task
- [x] Create menu items on home page
- [x] List menu items and their price
- [x] Link the menu items from the 'Menu' option

**Comment by bijokmathew** [comment]
all the listed task done and tested
